### ISSUE TITLE
Cannot access website

### ISSUE THREAD

**Issue by erm3nda** [tinypressco/tinypress#6]
Hi.

I am not sure if this repo is the proper site to ask about "the service" and not about "the code".
I see waybackmachine.org to ensure i am not totally dumb looking for tinypress.co, but seems is down.

What's the plan for it.
Case you won't put it online i would consider using just ssh to publis. It's a bit sad to have the publish tool offline those days with more free time.

Regards!

**Comment by IvanFon** [comment]
No reply... looks like Tinypress is dead?

**Comment by erm3nda** [comment]
@IvanFon 
I think dev is so bussy with other things, or maybe with the new version.

It's a bit "shame" to put down a service like that, instead of left the old service running untill the new version can be released.

I am considering to use the Github UI to publish instead 3rd party tools. Even publish with GIT will be better.

**Comment by dainmiller** [comment]
@IvanFon Hi! Trust me, I didnt close the site on purpose. If I could have left v1 up, I would have, but there was a server side issue with our backups and our primary instance and it was non recoverable. V1 was not using a very good dev-ops set up since it was a "quick and dirty" version, and therefore any sort of dev ops related tragedy that you didn't plan for has negative consequences.  

My apologies for having the downtime.

**Comment by erm3nda** [comment]
I've actually opt-in the v2 version, but know if there's any roadmap, calendar plans or estimated publishing date will make the difference between relax and wait for v2 or pick any of my other options

Ur app it's awesome, but non working from months is not a thing that i can easily ignore.

Best regards.

**Comment by dainmiller** [comment]
Sorry bud. No timelines right now.

It's a free app and I don't make any money off it, so there's a limit to how much I can work on it. Hope to launch v2 sometime soon :)
